// LISTA SVIH SIGNALA ZA DALEKOVODNO POLJE

public class listaSviDalekovodno {
	public String lista;
	
	listaSviDalekovodno () {
		lista = "*LISTA JE IZRAÐENA NA NAÈIN: NAZIV EEP-a, TEH.MODUL, TEH.JEDINICA, UREDJAJ, VARIJABLA, STANJE*\n"
		+ "---    LISTA SVIH SIGNALA DALEKOVODNOG POLJA    ---\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "komanda    " + "isklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "komanda    " + "uklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "stanje    " + "medjupoložaj\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "stanje    " + "ukljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "stanje    " + "iskljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "stanje    " + "kvar signalizacije\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "gubitak-SF6-upozorenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "gubitak-SF6-upozorenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "blokada-rada    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "blokada-rada    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "blokada-iskopa    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "blokada-iskopa    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "opruga-navijena-kvar    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "prekidac    " + "opruga-navijena-kvar    " + "prestanak\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "komanda    " + "isklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "komanda    " + "uklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "stanje    " + "medjupolozaj\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "stanje    " + "ukljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "stanje    " + "iskljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s1    " + "stanje    " + "kvar signalizacije\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "komanda    " + "isklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "komanda    " + "uklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "stanje    " + "medjupolozaj\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "stanje    " + "ukljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "stanje    " + "iskljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-sabirnicki-s2    " + "stanje    " + "kvar signalizacije\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "komanda    " + "isklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "komanda    " + "uklop\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "stanje    " + "medjupolozaj\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "stanje    " + "ukljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "stanje    " + "iskljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-izlazni    " + "stanje    " + "kvar signalizacije\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-uzemljenja    " + "stanje    " + "medjupolozaj\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-uzemljenja    " + "stanje    " + "ukljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-uzemljenja    " + "stanje    " + "iskljucen\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "rastavljac-uzemljenja    " + "stanje    " + "kvar signalizacije\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l1-poticaj    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l1-poticaj    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l2-poticaj    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l2-poticaj    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l3-poticaj    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "faza-l3-poticaj    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "zemljospoj-poticaj    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "zemljospoj-poticaj     " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "2.stupanj-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "2.stupanj-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "3.stupanj-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "3.stupanj-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "4.stupanj-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "4.stupanj-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "suprotni-smjer-poticaj    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "suprotni-smjer-poticaj    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "njihanje-energije-blokada    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "njihanje-energije-blokada    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-prijem    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-prijem    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-slanje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-slanje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "TK-signal-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "napajanje-nestanak    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "napajanje-nestanak    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "uredjaj-kvar    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "distantna-zastita    " + "uredjaj-kvar    " + "prestanak\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-ukljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-ukljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-1p    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-1p    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-3p    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-3p    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-blokada    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "apu    " + "apu-blokada    " + "prestanak\n\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "npc-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "npc-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "vpc-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "vpc-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "zemljospojna-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "zemljospojna-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "od-preopterecenja-upozorenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "od-preopterecenja-upozorenje    "        + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "od-preopterecenja-iskljucenje    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "od-preopterecenja-iskljucenje    " + "prestanak\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "relej-kvar    " + "prorada\n"
		+ "TS-G    " + "110    " + "DV Rijeka    " + "nadstrujna-zastita    " + "relej-kvar    " + "prestanak\n";
	}
}
